[package]
name = "client"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "ft"
path = "src/main.rs"
[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
common = { path = "../common" }
