[package]
name = "client"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "fr8"
path = "src/main.rs"
[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
common = { path = "../common" }
confy = "0.6.1"
serde = "1.0.217"
serde_derive = "1.0.217"
tokio = { version = "1.43.0", features = ["full"] }
url = "2.5.4"
