env_files = [".env.dev", ".env"]
[config]
default_to_workspace = false

[tasks.openapi-fetch]
command = "curl"
args = ["-o", "schema.yaml", "${BACKEND_REST_HOST}/api/schema.yaml"]
[tasks.openapi-gen]
command = "docker"
windows.env = { "PWD" = {script = [ "cd" ]}}
linux.env = { "UID" = { script = [
    "id -u",
] }, "GID" = { script = [
    "id -g",
] }, "OPTS" = "--user=${UID}:${GID}" }

args = [
    "run",
    "--rm",
    "@@remove-empty(OPTS)",
    "-v",
    "${PWD}:/local",
    "openapitools/openapi-generator-cli",
    "generate",
    "-i",
    "/local/schema.yaml",
    "-g",
    "rust",
    "-o",
    "/local/backend_api",
    "--skip-validate-spec",
]
[tasks.openapi]
dependencies = ["openapi-fetch", "openapi-gen"]
